export const employees = [
    {
        id: 1,
        name: 'Nguyễn Văn A',
        department: 'Sales',
        phone: '123-456-7890',
        gender: 'Nam',
        email: 'nguyenvana@example.com',
        bank: 'ACB Bank',
        birthday: '1990-05-15',
        address: '123 ABC Street, HCM City',
        nation: 'Vietnam',
        bankaccount: '123456789',
        color: '#FF5733',
        status: true
    },
    {
        id: 2,
        name: 'Trần Thị B',
        department: 'Marketing',
        phone: '987-654-3210',
        gender: 'Nữ',
        email: 'tranthib@example.com',
        bank: 'Vietcombank',
        birthday: '1988-09-20',
        address: '456 XYZ Street, Hanoi',
        nation: 'Vietnam',
        bankaccount: '987654321',
        color: '#3498DB',
        status: true
    },
    {
        id: 3,
        name: 'Lê Hoàng C',
        department: 'Finance',
        phone: '555-555-5555',
        gender: 'Nam',
        email: 'lehoangc@example.com',
        bank: 'Techcombank',
        birthday: '1995-03-10',
        address: '789 DEF Street, Da Nang',
        nation: 'Vietnam',
        bankaccount: '456789123',
        color: '#27AE60',
        status: false
    },
    {
        id: 4,
        name: 'Phạm Thị D',
        department: 'Operations',
        phone: '222-333-4444',
        gender: 'Nữ',
        email: 'phamthid@example.com',
        bank: 'BIDV',
        birthday: '1987-12-05',
        address: '567 GHI Street, Ho Chi Minh',
        nation: 'Vietnam',
        bankaccount: '789123456',
        color: '#E74C3C',
        status: true
    },
    {
        id: 5,
        name: 'Vũ Minh E',
        department: 'Engineering',
        phone: '666-777-8888',
        gender: 'Nam',
        email: 'vuminhe@example.com',
        bank: 'VietinBank',
        birthday: '1992-08-25',
        address: '234 JKL Street, Hue',
        nation: 'Vietnam',
        bankaccount: '369258147',
        color: '#F39C12',
        status: false
    },
    {
        id: 6,
        name: 'Hoàng Anh F',
        department: 'Customer Support',
        phone: '999-999-9999',
        gender: 'Nam',
        email: 'hoanganhf@example.com',
        bank: 'VPBank',
        birthday: '1993-04-30',
        address: '789 MNO Street, Quang Nam',
        nation: 'Vietnam',
        bankaccount: '9876543210',
        color: '#9B59B6',
        status: true
    },
    {
        id: 7,
        name: 'Ngô Thị G',
        department: 'Research & Development',
        phone: '123-123-1234',
        gender: 'Nữ',
        email: 'ngothig@example.com',
        bank: 'Sacombank',
        birthday: '1991-11-18',
        address: '345 PQR Street, Nha Trang',
        nation: 'Vietnam',
        bankaccount: '123789456',
        color: '#2980B9',
        status: false
    },
    {
        id: 8,
        name: 'Trần Đức H',
        department: 'Quality & Assurance',
        phone: '777-888-9999',
        gender: 'Nam',
        email: 'tranduch@example.com',
        bank: 'Agribank',
        birthday: '1994-06-12',
        address: '678 STU Street, Vung Tau',
        nation: 'Vietnam',
        bankaccount: '456123789',
        color: '#1ABC9C',
        status: true
    },
    {
        id: 9,
        name: 'Lý Thanh I',
        department: 'Design',
        phone: '888-777-5555',
        gender: 'Nữ',
        email: 'lythani@example.com',
        bank: 'MBBank',
        birthday: '1989-02-08',
        address: '890 VWX Street, Can Tho',
        nation: 'Vietnam',
        bankaccount: '789456123',
        color: '#8E44AD',
        status: false
    },
    {
        id: 10,
        name: 'Phan Tuấn J',
        department: 'Chăm sóc khách hàng',
        phone: '333-222-1111',
        gender: 'Nam',
        email: 'phantuanj@example.com',
        bank: 'DongA Bank',
        birthday: '1996-07-22',
        address: '901 YZA Street, Hai Phong',
        nation: 'Vietnam',
        bankaccount: '369147258',
        color: '#E67E22',
        status: true
    },
];
